### PR TITLE
A few changes to chapter 8

### PR DESCRIPTION
**Pull request by Sleepykoh**

### CODE REVIEW

**Comment by ItaloKnox** [comment]
There are some valid changes but most of your changes aren't matching the japanese text. I think you should double check it.

**Comment by Sleepykoh** [comment]
Which changes are valid?

**Comment by ItaloKnox** [comment]
Anything that doesn't involve taking out words/sentences and switching words to others who aren't exact synonyms.

The patch is currently at optimum performance. We just hit v1.5. At this moment, the only thing left to fix is a typo or two.

**Comment by Sleepykoh** [comment]
Alright. What about the changes to the scene with the caller? Previously Keiichi refers to them as a girl but then he starts referring to them as "man" and "him". The voice is also that of a girl.

**Comment by ItaloKnox** [comment]
I've spent more time making the patch than actually reading the novel, so I'm unsure about that scene in particular. Perhaps @Norgus can give his input on that.

**Pull request closed without merging**
