### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ghost**
I don't know if this must be androgynous to fit with both the original or updated script. 
If it must be androgynous, try: `talking to her` --> `on the phone`. 
That text should fit and won't contradict the Japanese.

### CODE REVIEW

**Comment by P-Chang** [comment]
@enumag 
Sorry, miss clicking.

**Comment by P-Chang** [comment]
I think `on the phone` is natural too and compatible with both scripts.
But my English skill is lowest in team, so I leave it to @ItaloKnox or @DoctorDiablo.

**Comment by ItaloKnox** [comment]
Sure, I think it works. Can you commit the right changes so someone can merge it? I don't really have much time to commit it right now.

**Comment by P-Chang** [comment]
OK, I finished it. thanks.

**Pull request merged**
