### PR TITLE
Fixes to in-game typos

### PR DESCRIPTION
**Pull request by Darbury**
Just fixing a handful of spelling errors that made it into the Steam release.

### CODE REVIEW

**Comment by orian34** [comment]
Again, seems good, not sure why the need to change guerilla, travelling and neighbouring, which are all valid

**Comment by Darbury** [comment]
re: "guerilla, travelling and neighbouring"
MangaGamer has edited the game to US English standards (which is why we see "color" throughout rather than "colour"). The three above words are typically considered UK spelling variants and fall out from that US standard.

If we want to keep these variants in, we totally can. We should just be aware that we're mixing two different sets of spellings, which can stand out to the reader.

**Comment by TellowKrinkle** [comment]
If you're going to capitalize part of "blue hawaii" capitalize the whole thing

**Comment by Darbury** [comment]
I’ve seen it both ways — e.g., https://www.thespruceeats.com/blue-hawaiian-recipe-759284 — but agreed that googling seems to show having the B & H capitalized is more common. (And having neither capitalized is just not a thing.) 😀

**Pull request merged**
