### PR TITLE
wata_011_02.txt Corrected phone call text

### PR DESCRIPTION
**Pull request by nakigoe**
殺されちゃった sent them to their forefathers
(and some other tiny details)

<h1><a href="https://nakigoe.github.io">nakigoe.github.io</a></h1>

### CODE REVIEW

**Comment by orian34** [comment]
I'm not sure I agree with some of these changes, mh, I wonder, what do @enumag  think?

**Comment by enumag** [comment]
Since these seems to be translation fixes I'm not the right person to ask. We'll need @Norgus, @DoctorDiablo or @ItaloKnox to review this.

**Comment by Norgus** [comment]
I disagree with that rather strange choice "sent them to their forefathers", and also don't really think the modifications should be made - they seem to be editorial taste as much as anything (which I think is a bit beyond the scope of what we can practically do to the whole game script).

**Comment by enumag** [comment]
Thanks, Norgus. Closing then.

**Pull request closed without merging**
