### PR TITLE
Fix Mion/Shion

### PR DESCRIPTION
**Pull request by enumag**
Make sure that this change is correct before merging please.

I don't recall Mion ever going to Angel Mort, it was Shion all the time and it was also Shion who told Keichi about the dam project - right?

Can you check the japanese version as well?

### CODE REVIEW

**Comment by Norgus** [comment]
uh, copy-pasting my comment here>

The Japanese matches the text as it was before the change. (Shion - 詩音 first, corrected to Mion - 魅音 second)

This must be from when Keiichi is still convinced that Shion is an act put on by Mion.

**Comment by enumag** [comment]
It is not. This is right before watanagashi when Keichi is already aware that they are indeed twins. In fact just a few lines above there is Keichi, Shion and Mion all together.

**Comment by Norgus** [comment]
Oh yeah, that's weird... But the Japanese is Keiichi correcting himself from Shion to Mion still.

**Comment by enumag** [comment]
Then perhaps the error originated in the japanese text and the translator didn't catch it?

**Comment by enumag** [comment]
Hmm the error is not just this one line. The following lines also seem to suggest that it was Mion who told Keichi about the dam project instead of Shion. But still I'm positive that it was Shion (at least in Watanagashi-hen).

**Comment by Norgus** [comment]
I'll try re-reading from wata_004 (the scene where he hears about the dam project from.. whoever is being Shion lol) at some point, see if I can figure out a good reason for Keiichi to still be thinking it was Mion at Angel Mort.

**Comment by enumag** [comment]
Or perhaps Keichi was talking with Mion about it as well (at school maybe)? I couldn't find such conversation either though. Anyway thanks.

**Comment by Norgus** [comment]
I've been re-reading, and there is a part that sounds like Keiichi knows/believes that the Shion at Angel Mort on the desert festival day was actually Mion pretending to be Shion.
https://github.com/higurashi-mod/watanagashi/blob/master/Update/wata_007.txt#L1622-L1655

So I googled it a bit too, and found this
http://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1431098804
The question is 

"In Watanagashi-hen, who is the first one to make an appearance in Angel Mort, Mion or Shion?"
and most people (including the selected "correct" answer) seem to think it was Mion pretending to be Shion.

Then, after the first Angel Mort encounter, on the way home from school, Keiichi notices he lost his keys and Mion tells him that they found the keys at Angel Mort, then acts all flustered and makes the excuse that Shion told her.
https://github.com/higurashi-mod/watanagashi/blob/master/Update/wata_004.txt#L2076-L2093

So it seems like Keiichi did realize that it was Mion pretending to be Shion at Angel Mort on both the first time and at the desert festival - but it was actually Shion on the day that they end up "dating" and upsetting Mion at the toy store.

sooo - I don't think there's a problem with the Japanese text, and I feel like I learned a bit about the story which I wouldn't have otherwise (not very observant + bad memory :( )

**Comment by enumag** [comment]
Wow this is interesting. I really believed that it was always Shion in Angel Mort but it was in fact both of them?! Hard to believe - her behavior in Angel Mort always seemed Shion-like to me but of course it could have sometimes been Mion pretending. It's hard to tell though what was each of them telling the other though. If I'm not mistaken the "Shion" in Angel Mort always knew about the events from previous encounter.

Maybe the reader is not even supposed to know which twin was in which scene. And of course what Keichi believes might be off as well.

Thanks for your research on this matter. I think I love Higurashi even more now.

**Pull request closed without merging**
